services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env  
    depends_on:
      - db
    command: flask run --host=0.0.0.0 --port=5000

  db:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"